### ISSUE TITLE
Build failure with default Ubuntu 16.04 node, which is version 4.2.6

### ISSUE THREAD

**Issue by uhofemei** [otcshare/iotivity-node#111]
Hi, I can't seem to build iotivity-node against the default version of node that is part of the Ubuntu 16.04 repository either. Here's  the error message.

ulf@gateway-new:~/lab/iotivity-node$ npm install

> iotivity-node@1.2.0-2 install /home/ulf/lab/iotivity-node
> node-gyp rebuild

make: Entering directory '/home/ulf/lab/iotivity-node/build'
  ACTION Building CSDK iotivity-installed
fs.js:808
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/home/ulf/lab/iotivity-node/iotivity-native/out'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at findBins (/home/ulf/lab/iotivity-node/build-scripts/build-csdk.js:41:16)
    at Object.<anonymous> (/home/ulf/lab/iotivity-node/build-scripts/build-csdk.js:118:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
csdk.target.mk:13: recipe for target 'iotivity-installed' failed
make: *** [iotivity-installed] Error 1
make: Leaving directory '/home/ulf/lab/iotivity-node/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-31-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/ulf/lab/iotivity-node
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! iotivity-node@1.2.0-2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iotivity-node@1.2.0-2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iotivity-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iotivity-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iotivity-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ulf/lab/iotivity-node/npm-debug.log
ulf@gateway-new:~/lab/iotivity-node$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@4.2.6 | linux | x64
gyp info spawn python2
gyp info spawn args [ '/usr/share/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ulf/lab/iotivity-node/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/include/nodejs/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
gyp info spawn args   '-Dnode_gyp_dir=/usr/share/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ulf/lab/iotivity-node',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/ulf/lab/iotivity-node/build'
  ACTION Building CSDK iotivity-installed
fs.js:808
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/home/ulf/lab/iotivity-node/iotivity-native/out'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at findBins (/home/ulf/lab/iotivity-node/build-scripts/build-csdk.js:41:16)
    at Object.<anonymous> (/home/ulf/lab/iotivity-node/build-scripts/build-csdk.js:118:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
csdk.target.mk:13: recipe for target 'iotivity-installed' failed
make: *** [iotivity-installed] Error 1
make: Leaving directory '/home/ulf/lab/iotivity-node/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-31-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/ulf/lab/iotivity-node
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

**Comment by uhofemei** [comment]
Please disregard. After the previous attempt to build iotivity-node against latest nodejs I never cleaned up the iotivity-node repository. Throwing it away and cloning a pristine tree allows me to build it for node version 4.2.6.
