### ISSUE TITLE
On Ubuntu, "nodejs-legacy" has to be installed in order to install "iotivity-node"

### ISSUE THREAD

**Issue by gvancuts** [otcshare/iotivity-node#149]
You must have `nodejs-legacy` installed on Ubuntu systems in order to be able to install `iotivity-node` (`npm install iotivity-node`). Otherwise, the installation fails as it does not find the `node` executable (see the full error message below. Given that `nodejs-legacy` seems to do nothing more than installing a symlink called `node` that points at `nodejs`, isn't there a way we could be a little more clever and use `nodejs` directly? (**Note**: I'm not sure whether this is something that can be solved as part of this project but if so, I believe we should do it).

Full error message:
```
gvancuts@gvancuts-nuc:~/SmartHome-Demo/ocf-servers$ npm install

> iotivity-node@1.3.0-1 install /home/gvancuts/SmartHome-Demo/ocf-servers/node_modules/iotivity-node
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -p "( process.env.OCTBSTACK_CFLAGS && process.env.OCTBSTACK_LIBS ) ? 'true' : 'false';"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-92-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/gvancuts/SmartHome-Demo/ocf-servers/node_modules/iotivity-node
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
SmartHome-Demo@0.1.0 /home/gvancuts/SmartHome-Demo/ocf-servers
├── lodash.assignin@4.2.0 
├── lodash.mergewith@4.6.0 
└── uuid@2.0.3

npm ERR! Linux 4.4.0-92-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! iotivity-node@1.3.0-1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iotivity-node@1.3.0-1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iotivity-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iotivity-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iotivity-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gvancuts/SmartHome-Demo/ocf-servers/npm-debug.log
```

**Comment by gabrielschulhof** [comment]
I run node commands from binding.gyp. I'll have to see if the path to the node binary is available in the environment somewhere.

**Comment by gabrielschulhof** [comment]
@gvancuts I don't know if there's a lot I can do, unfortunately. I kind of have to assume that `node` is on the PATH.

**Comment by gabrielschulhof** [comment]
I'll make a note in the documentation.

**Comment by gvancuts** [comment]
Hi @gabrielschulhof , I agree, I looked a (little) bit into this yesterday but did not come up with any good solution. A note in the doc seems the most appropriate course of action. Thanks!
