### ISSUE TITLE
Fail to build from HEAD

### ISSUE THREAD

**Issue by ttzeng** [otcshare/iotivity-node#168]
The build of iotivity-node from the current [master](https://github.com/otcshare/iotivity-node/tree/a587c84a95193de3cf1dee0b712cbe62785ec659) abort with the following errors:
```
npm WARN engine grunt-istanbul@0.7.2: wanted: {"node":"~0.12.0"} (current: {"node":"4.6.2","npm":"2.15.11"})
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
 
> commitplease@2.7.10 install /home/ubuntu/snap-recipes/ocf-util/parts/iotivity-node/build/node_modules/commitplease
> node install

npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated qunitjs@2.4.1: 2.4.1 is the last version where QUnit will be published as 'qunitjs'. To receive future updates, you will need to change the package name to 'qunit'.
npm WARN optional dep failed, continuing fsevents@1.1.3
-
> spawn-sync@1.0.15 postinstall /home/ubuntu/snap-recipes/ocf-util/parts/iotivity-node/build/node_modules/grunt-esformatter/node_modules/esformatter/node_modules/npm-run/node_modules/spawn-sync
> node postinstall


> iotivity-node@1.3.1-0 install /home/ubuntu/snap-recipes/ocf-util/parts/iotivity-node/build
> node-gyp rebuild

make: Entering directory '/home/ubuntu/snap-recipes/ocf-util/parts/iotivity-node/build/build'
  ACTION Building CSDK iotivity-installed
Cloning into '/home/ubuntu/snap-recipes/ocf-util/parts/iotivity-node/build/iotivity-native'...
remote: Counting objects: 4146, done
remote: Finding sources: 100% (4147/4147)
remote: Total 4147 (delta 330), reused 2521 (delta 330)
Receiving objects: 100% (4147/4147), 14.31 MiB | 13.81 MiB/s, done.
Resolving deltas: 100% (330/330), done.
Checking connectivity... done.
Note: checking out '633dc231b8d9967520627528a92506efca7cebcd'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

warning: extlibs/sqlite3/SConscript has type 100644, expected 100755
error: patch failed: build_common/SConscript:55
error: build_common/SConscript: patch does not apply
csdk.target.mk:13: recipe for target 'iotivity-installed' failed
make: *** [iotivity-installed] Error 1
make: Leaving directory '/home/ubuntu/snap-recipes/ocf-util/parts/iotivity-node/build/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/snap-recipes/ocf-util/stage/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.10.0-42-generic
gyp ERR! command "/home/ubuntu/snap-recipes/ocf-util/stage/bin/node" "/home/ubuntu/snap-recipes/ocf-util/stage/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/snap-recipes/ocf-util/parts/iotivity-node/build
gyp ERR! node -v v4.6.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Linux 4.10.0-42-generic
npm ERR! argv "/home/ubuntu/snap-recipes/ocf-util/stage/bin/node" "/home/ubuntu/snap-recipes/ocf-util/stage/bin/npm" "install"
npm ERR! node v4.6.2
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! iotivity-node@1.3.1-0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iotivity-node@1.3.1-0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the iotivity-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iotivity-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls iotivity-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/snap-recipes/ocf-util/parts/iotivity-node/build/npm-debug.log
```

**Comment by xiaoyu3x** [comment]
hi, @ttzeng 
I just used two methods to install 'iotivity-node' on my PC.
One way:
`npm install iotivity-node`
Another way:
`git clone https://github.com/otcshare/iotivity-node`
`npm install`
But your issue isn't reproduced on my side.
My PC:
ubuntu: 16.04
git version: 2.7.4
node version :6.11.0

Can you reproduce this issue and provide your steps?

**Comment by ttzeng** [comment]
Thanks @xiaoyu3x for the confirmation. It turns out the failure was caused by my previous patch for compiling iotivity for 32-bit platforms, the upstream release has fixed the build issue for 32-bit platforms.
