### ISSUE TITLE
Error on calling client. updateResource(USVString resourceId, OicResourceInit resource)

### ISSUE THREAD

**Issue by nagineni** [otcshare/iotivity-node#27]
Step1: Create a client example and call updateResource() on resoucefound event.
```javascript
device.client.updateResource(event.resource.id, event.resource);
```

Step2: Create a server example and send response back when the update event is proceed.

```javascript
      if ( request.type === "update" ) {
          request.sendResponse( null );
       }
```
Step3: Start server and client.

Actual outcome:
```javascript
iotivity-node/lib/OicClient.js:291
			_.extend( this._resources[ id ].properties, resource.properties );
			                         ^
TypeError: Cannot read property 'id' of undefined
    at updateResourceFromResponse (iotivity-node/lib/OicClient.js:291:29)
    at oneShotRequestHandler (iotivity-node/lib/OicClient.js:70:31)
    at wrapper [as _onTimeout] (timers.js:274:14)
    at Timer.listOnTimeout (timers.js:119:15)
```

**Comment by zolkis** [comment]
I think you should not pass ```null``` to ```sendResponse()```. The ```OicResourceInit``` needs to be passed (resource representation).

**Comment by nagineni** [comment]
Result is same with the resource representation too.

**Comment by nagineni** [comment]
@gabrielschulhof, thanks for fixing this.
