### ISSUE TITLE
Failed to require ('iotivity-node')('server') on Ostro image#449

### ISSUE THREAD

**Issue by wanghongjuan** [otcshare/iotivity-node#50]
#### Steps to reproduce
All upstream tests can run normally on Ostro image#449.

Connect the test device and run command:
```
root@edison:~# cd /usr/lib/node_modules/iotivity-node/tests/tests/
root@edison:~# node
> require('iotivity-node')('server');
> require('../../index')('server');
```

#### Board information

Target OS and platform:Edison and Ostro image#449(https://download.ostroproject.org/builds/ostro-os/2016-05-15_04-51-11-build-449/images/edison/ostro-image-swupd-dev-edison.toflash.tar.bz2)

#### Logs
```
root@edison:~# node
> require('iotivity-node')('server');
TypeError: Cannot read property 'length' of undefined
    at Sha256.Hash.update (/usr/lib/node_modules/iotivity-node/node_modules/sha.js/hash.js:16:28)
    at new StorageHandler (/usr/lib/node_modules/iotivity-node/lib/StorageHandler.js:56:20)
    at _.extend._startStack (/usr/lib/node_modules/iotivity-node/lib/OicDevice.js:149:49)
    at _.extend._startStack (/usr/lib/node_modules/iotivity-node/lib/OicServer.js:105:11)
    at _.extend._construct (/usr/lib/node_modules/iotivity-node/lib/OicDevice.js:51:8)
    at _.extend._construct (/usr/lib/node_modules/iotivity-node/lib/OicClient.js:43:18)
    at _.extend._construct (/usr/lib/node_modules/iotivity-node/lib/OicServer.js:96:18)
    at new OicDevice (/usr/lib/node_modules/iotivity-node/lib/OicDevice.js:24:8)
    at OicDevice (/usr/lib/node_modules/iotivity-node/lib/OicDevice.js:21:11)
    at repl:1:25  
> require(‘../../index')('server');
TypeError: Cannot read property 'length' of undefined
    at Sha256.Hash.update (/usr/lib/node_modules/iotivity-node/node_modules/sha.js/hash.js:16:28)
    at new StorageHandler (/usr/lib/node_modules/iotivity-node/lib/StorageHandler.js:56:20)
    at _.extend._startStack (/usr/lib/node_modules/iotivity-node/lib/OicDevice.js:149:49)
    at _.extend._startStack (/usr/lib/node_modules/iotivity-node/lib/OicServer.js:105:11)
    at _.extend._construct (/usr/lib/node_modules/iotivity-node/lib/OicDevice.js:51:8)
    at _.extend._construct (/usr/lib/node_modules/iotivity-node/lib/OicClient.js:43:18)
    at _.extend._construct (/usr/lib/node_modules/iotivity-node/lib/OicServer.js:96:18)
    at new OicDevice (/usr/lib/node_modules/iotivity-node/lib/OicDevice.js:24:8)
    at OicDevice (/usr/lib/node_modules/iotivity-node/lib/OicDevice.js:21:11)
    at repl:1:25  
```
But it's work well when run `require('iotivity-node')('client')`.
I find the code `var oic = require( "../../../index" )( "server" );` is used in the server.js of upstream tests.

**Comment by gabrielschulhof** [comment]
I have found the root cause for this issue and I've fixed it. It will be available in the next release of iotivity-node. This issue is not a high priority though, because it only manifests itself when you try to ```require( "iotivity-node" )( "server" );``` interactively. If you instead create a file *something.js* that contains ```require( "iotivity-node" )( "server" );``` and run it with ```node ./something.js``` then there will be no error.

**Comment by wanghongjuan** [comment]
Many thanks for response, I tried to rerun the command following your comment and it worked well.

**Comment by gabrielschulhof** [comment]
I've actually included a fix that will make it possible to ```require()``` iotivity-node from an interactive node.js session. I will push the fix as part of the next release.
