### ISSUE TITLE
Failed to run example in the spec iot-js-spec.md on Ostro image#449

### ISSUE THREAD

**Issue by wanghongjuan** [otcshare/iotivity-node#51]
As the spec content that the command `var oic = require('oic');` should work well on target device, but failed.
#### Step to reproduce
```
root@edison:~# node
> var oic = require('oic');
Error: Cannot find module 'oic'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at repl:1:11
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:427:12)
    at emitOne (events.js:82:20)
> 
```

#### Board information

Target OS and platform:Edison and Ostro image#449(https://download.ostroproject.org/builds/ostro-os/2016-05-15_04-51-11-build-449/images/edison/ostro-image-swupd-dev-edison.toflash.tar.bz2)

**Comment by gabrielschulhof** [comment]
I don't believe the way in which you perform the ```require()``` call is part of the spec - only the way the resulting object behaves.

The part of the example in the spec that reads ```require( "oic" )``` is just that - an example. With the actual implementation you need to write ```require( "iotivity-node" )```.
