### ISSUE TITLE
urlopen error occurs when npm install iotivity-node on Ostro

### ISSUE THREAD

**Issue by haoxli** [otcshare/iotivity-node#58]
Hi,

I install iotivity-node via `npm install iotivity-node` on Ostro[1] after resolved dependencies in [IoTivity-node](https://www.npmjs.com/package/iotivity-node), but `SSL: CERTIFICATE_VERIFY_FAILED` error occurs when scons download [gtest](https://googletest.googlecode.com/files/gtest-1.7.0.zip).
```
 gtest_zip = env.Download(gtest_zip_file, gtest_url)
```
Error log:
```
scons: warning: Ignoring missing SConscript 'out/linux/x86_64/release/resource/csdk/connectivity/samples/linux/SConscript'
File "/usr/lib/node_modules/iotivity-node/depbuild/iotivity-1.1.0-3003bf3/resource/csdk/connectivity/SConscript", line 92, in <module>
*** Checking for installation of google unit test 1.7.0 ***
Download /usr/lib/node_modules/iotivity-node/depbuild/iotivity-1.1.0-3003bf3/extlibs/gtest/gtest-1.7.0.zip from https://googletest.googlecode.com/files/gtest-1.7.0.zip
Downloading ...
scons: *** <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)> [https://googletest.googlecode.com/files/gtest-1.7.0.zip]  Stop.
+ cat config.log
file /usr/lib/node_modules/iotivity-node/depbuild/iotivity-1.1.0-3003bf3/build_common/SConscript,line 408:
        Configure(confdir = .sconf_temp)
scons: Configure: Checking for POSIX Thread Support...
.sconf_temp/conftest_0.c <-
  |
  |#if !defined(__GNUC__)
  |#  error "Not the GCC C compiler."
  |#endif
  |
  |int foo(void)
  |{
  |    return 0;
  |}
  |
Compiling .sconf_temp/conftest_0.o
.sconf_temp/conftest_1.c <-
  |
  |#include <unistd.h>
  |#include <pthread.h>
  |int main()
  |{
  |    #ifndef _POSIX_THREADS
  |    # error POSIX Threads support not available
  |    #endif
  |    return 0;
  |}
  |
Compiling .sconf_temp/conftest_1.o
scons: Configure: yes
 
 
file /usr/lib/node_modules/iotivity-node/depbuild/iotivity-1.1.0-3003bf3/resource/third_party_libs.scons,line 49:
        Configure(confdir = .sconf_temp)
 
file /usr/lib/node_modules/iotivity-node/depbuild/iotivity-1.1.0-3003bf3/resource/third_party_libs.scons,line 49:
        Configure(confdir = .sconf_temp)
 
file /usr/lib/node_modules/iotivity-node/depbuild/iotivity-1.1.0-3003bf3/resource/third_party_libs.scons,line 49:
        Configure(confdir = .sconf_temp)
 
file /usr/lib/node_modules/iotivity-node/depbuild/iotivity-1.1.0-3003bf3/resource/third_party_libs.scons,line 49:
        Configure(confdir = .sconf_temp)
 
file /usr/lib/node_modules/iotivity-node/depbuild/iotivity-1.1.0-3003bf3/resource/third_party_libs.scons,line 49:
        Configure(confdir = .sconf_temp)
 
file /usr/lib/node_modules/iotivity-node/depbuild/iotivity-1.1.0-3003bf3/resource/third_party_libs.scons,line 49:
        Configure(confdir = .sconf_temp)
 
+ exit 1
csdk.target.mk:13: recipe for target 'deps/iotivity' failed
make: *** [deps/iotivity] Error 1
make: Leaving directory '/usr/lib/node_modules/iotivity-node/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.12-yocto-standard
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/iotivity-node
gyp ERR! node -v v4.4.1
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok 
npm ERR! Linux 4.4.12-yocto-standard
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "iotivity-node"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
```

Find an answer in http://stackoverflow.com/questions/27835619/ssl-certificate-verify-failed-error
Hope it would help.

[1] https://download.ostroproject.org/builds/ostro-os/2016-06-16_08-11-07-build-464/images/intel-corei7-64/ostro-image-swupd-dev-intel-corei7-64.dsk.zip

**Comment by nagineni** [comment]
Iotivity is failing to download the gtest on Ostro due to the missing certs. There is a bug in iotivity jira already:  https://jira.iotivity.org/browse/IOT-820

We also don't seem to have the `scons` tool in Ostro images. So, you probably need to file a bug in Ostro, if it is really needed.
